[project]
name = "data-store-360"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohamed", email = "mohamedsehrane314@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.5",
]

[project.scripts]
data-store-360 = "data_store_360:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
